def t(lang: str, code: str) -> str:
    source = TEXTS.get(lang, TEXTS["en"])
    return source[code] if code in source else TEXTS["en"][code]


TEXTS = {
    "ru": {
        "start_title": "My TON Provider",
        "start_body": "<b>Отслеживайте статус провайдеров</b> — телеметрия, уведомления и многое другое.",
        "open_app": "Открыть приложение",
        "alert_provider": "Провайдер:",
        "alert_providers": "Провайдеры:",
        "alert_restarted": "Сервис {service} перезапущен",
        "bag_added_title": "Добавлен бэг",
        "bag_stored_title": "Бэг скачался",
        "bag_slow_title": "Бэг качается слишком долго",
        "bag_removed_title": "Провайдер снят с бэга",
        "bag_unpaid_title": "Закончились средства на бэге",
        "bag_closed_title": "Бэг закрыт владельцем",
        "bag_refilled_title": "Бэг снова оплачивается",
        "channel_bag_added_title": "Добавлен новый бэг",
        "channel_bag_changed_title": "Состав провайдеров изменён",
        "bag_id": "Бэг:",
        "bag_content": "Содержимое:",
        "bag_contract": "Контракт:",
        "bag_owner": "Владелец:",
        "list_more": "… и ещё {n}",
        "report_daily_title": "Ежедневный отчёт",
        "report_monthly_title": "Ежемесячный отчёт",
        "report_earned": "Заработано:",
        "report_space": "Прирост места:",
        "report_bags": "Добавлено бэгов:",
        "report_traffic_in": "Трафик входящий:",
        "report_traffic_out": "Трафик исходящий:",
        "alert_detected_not_online": "Провайдер офлайн",
        "alert_detected_telemetry_lost": "Телеметрия не поступает",
        "alert_detected_cpu_high": "Повышенная нагрузка CPU",
        "alert_detected_ram_high": "Повышенная загрузка RAM",
        "alert_detected_network_high": "Повышенная нагрузка сети",
        "alert_detected_disk_load_high": "Повышенная нагрузка на диск",
        "alert_detected_disk_space_low": "Заканчивается место на диске",
        "alert_resolved_not_online": "Провайдер снова онлайн",
        "alert_resolved_telemetry_lost": "Телеметрия снова поступает",
        "alert_resolved_cpu_high": "Нагрузка CPU нормализовалась",
        "alert_resolved_ram_high": "Загрузка RAM нормализовалась",
        "alert_resolved_network_high": "Нагрузка сети нормализовалась",
        "alert_resolved_disk_load_high": "Нагрузка на диск нормализовалась",
        "alert_resolved_disk_space_low": "Место на диске восстановлено",
    },
    "en": {
        "start_title": "My TON Provider",
        "start_body": "<b>Track your providers' status</b> —\ntelemetry, notifications and much more.",
        "open_app": "Open the app",
        "alert_provider": "Provider:",
        "alert_providers": "Providers:",
        "alert_restarted": "Service {service} restarted",
        "bag_added_title": "Bag added",
        "bag_stored_title": "Bag downloaded",
        "bag_slow_title": "Bag is taking too long to download",
        "bag_removed_title": "Provider removed from the bag",
        "bag_unpaid_title": "The bag ran out of funds",
        "bag_closed_title": "The owner closed the bag",
        "bag_refilled_title": "The bag is funded again",
        "channel_bag_added_title": "New bag added",
        "channel_bag_changed_title": "Providers updated",
        "bag_id": "Bag:",
        "bag_content": "Content:",
        "bag_contract": "Contract:",
        "bag_owner": "Owner:",
        "list_more": "… and {n} more",
        "report_daily_title": "Daily report",
        "report_monthly_title": "Monthly report",
        "report_earned": "Earned:",
        "report_space": "Space added:",
        "report_bags": "Bags added:",
        "report_traffic_in": "Traffic in:",
        "report_traffic_out": "Traffic out:",
        "alert_detected_not_online": "Provider is not online",
        "alert_detected_telemetry_lost": "Telemetry stopped coming in",
        "alert_detected_cpu_high": "Elevated CPU load",
        "alert_detected_ram_high": "Elevated RAM usage",
        "alert_detected_network_high": "Elevated network load",
        "alert_detected_disk_load_high": "Elevated disk load",
        "alert_detected_disk_space_low": "Disk space running low",
        "alert_resolved_not_online": "Provider is back online",
        "alert_resolved_telemetry_lost": "Telemetry is coming in again",
        "alert_resolved_cpu_high": "CPU load is back to normal",
        "alert_resolved_ram_high": "RAM usage is back to normal",
        "alert_resolved_network_high": "Network load is back to normal",
        "alert_resolved_disk_load_high": "Disk load is back to normal",
        "alert_resolved_disk_space_low": "Disk space recovered",
    },
}
