"""initial schema

Every table the app has, squashed from the migrations that grew it. A live database is
stamped with this revision after the schema it already has is compared with the one this
file builds.

Revision ID: b5e3847e131c
Revises: 
Create Date: 2026-08-30 08:52:48.291124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.db.models._base import UTCDateTime


# revision identifiers, used by Alembic.
revision: str = 'b5e3847e131c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_channels',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('invite_link', sa.String(length=128), nullable=True),
    sa.Column('address', sa.String(length=64), nullable=True),
    sa.Column('lang', sa.String(length=8), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('chat_id', name=op.f('pk_alert_channels')),
    sa.UniqueConstraint('address', 'lang', name='uq_alert_channels_address_lang')
    )
    op.create_table('bags',
    sa.Column('address', sa.String(length=64), nullable=False),
    sa.Column('bag_id', sa.String(length=64), nullable=True),
    sa.Column('owner_address', sa.String(length=64), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('chunk_size', sa.Integer(), nullable=True),
    sa.Column('merkle_hash', sa.String(length=64), nullable=True),
    sa.Column('key_len', sa.Integer(), nullable=True),
    sa.Column('balance', sa.BigInteger(), nullable=True),
    sa.Column('state', sa.String(length=16), server_default='not_hired', nullable=False),
    sa.Column('unpaid_at', UTCDateTime(), nullable=True),
    sa.Column('closed_at', UTCDateTime(), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('address', name=op.f('pk_bags'))
    )
    with op.batch_alter_table('bags', schema=None) as batch_op:
        batch_op.create_index('ix_bags_bag_id', ['bag_id'], unique=False)
        batch_op.create_index('ix_bags_owner_address', ['owner_address'], unique=False)
        batch_op.create_index('ix_bags_state', ['state'], unique=False)
        batch_op.create_index('ix_bags_unpaid_at', ['unpaid_at'], unique=False)

    op.create_table('providers',
    sa.Column('pubkey', sa.String(length=64), nullable=False),
    sa.Column('listed', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('min_span', sa.Integer(), nullable=True),
    sa.Column('max_span', sa.Integer(), nullable=True),
    sa.Column('max_bag_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('min_rate_per_mb_day', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.Column('balance_at', UTCDateTime(), nullable=True),
    sa.Column('last_online_at', UTCDateTime(), nullable=True),
    sa.Column('registered_at', UTCDateTime(), nullable=True),
    sa.Column('wallet_address', sa.String(length=64), nullable=False),
    sa.Column('cpu_load_percent', sa.Float(), nullable=True),
    sa.Column('ram_load_percent', sa.Float(), nullable=True),
    sa.Column('disk_load_percent', sa.Float(), nullable=True),
    sa.Column('net_mbps', sa.Float(), nullable=True),
    sa.Column('net_capacity_mbps', sa.Float(), nullable=True),
    sa.Column('net_load_pct', sa.Float(), nullable=True),
    sa.Column('disk_used', sa.BigInteger(), nullable=True),
    sa.Column('disk_total', sa.BigInteger(), nullable=True),
    sa.Column('last_wallet_lt', sa.BigInteger(), nullable=True),
    sa.Column('last_bytes_recv', sa.BigInteger(), nullable=True),
    sa.Column('last_bytes_sent', sa.BigInteger(), nullable=True),
    sa.Column('balance', sa.BigInteger(), nullable=True),
    sa.Column('earned', sa.BigInteger(), nullable=False),
    sa.Column('traffic_in', sa.BigInteger(), nullable=False),
    sa.Column('traffic_out', sa.BigInteger(), nullable=False),
    sa.Column('telemetry_pass', sa.String(length=255), nullable=True),
    sa.Column('telemetry_at', UTCDateTime(), nullable=True),
    sa.Column('ton_storage_uptime', sa.Float(), nullable=True),
    sa.Column('ton_storage_githash', sa.String(length=40), nullable=True),
    sa.Column('ton_storage_provider_uptime', sa.Float(), nullable=True),
    sa.Column('ton_storage_provider_githash', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('pubkey', name=op.f('pk_providers'))
    )
    op.create_table('providers_history',
    sa.Column('pubkey', sa.String(length=64), nullable=False),
    sa.Column('archived_at', UTCDateTime(), nullable=False),
    sa.Column('wallet_address', sa.String(length=64), nullable=False),
    sa.Column('cpu_load_percent', sa.Float(), nullable=True),
    sa.Column('ram_load_percent', sa.Float(), nullable=True),
    sa.Column('disk_load_percent', sa.Float(), nullable=True),
    sa.Column('net_mbps', sa.Float(), nullable=True),
    sa.Column('net_capacity_mbps', sa.Float(), nullable=True),
    sa.Column('net_load_pct', sa.Float(), nullable=True),
    sa.Column('disk_used', sa.BigInteger(), nullable=True),
    sa.Column('disk_total', sa.BigInteger(), nullable=True),
    sa.Column('last_wallet_lt', sa.BigInteger(), nullable=True),
    sa.Column('last_bytes_recv', sa.BigInteger(), nullable=True),
    sa.Column('last_bytes_sent', sa.BigInteger(), nullable=True),
    sa.Column('balance', sa.BigInteger(), nullable=True),
    sa.Column('earned', sa.BigInteger(), nullable=False),
    sa.Column('traffic_in', sa.BigInteger(), nullable=False),
    sa.Column('traffic_out', sa.BigInteger(), nullable=False),
    sa.Column('telemetry_pass', sa.String(length=255), nullable=True),
    sa.Column('telemetry_at', UTCDateTime(), nullable=True),
    sa.Column('ton_storage_uptime', sa.Float(), nullable=True),
    sa.Column('ton_storage_githash', sa.String(length=40), nullable=True),
    sa.Column('ton_storage_provider_uptime', sa.Float(), nullable=True),
    sa.Column('ton_storage_provider_githash', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('pubkey', 'archived_at', name=op.f('pk_providers_history'))
    )
    with op.batch_alter_table('providers_history', schema=None) as batch_op:
        batch_op.create_index('ix_providers_history_archived_at', ['archived_at'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('fullname', sa.String(length=129), nullable=True),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.Column('lang', sa.String(length=8), nullable=False),
    sa.Column('theme', sa.String(length=8), nullable=False),
    sa.Column('explorer', sa.String(length=16), nullable=False),
    sa.Column('favorites', sa.JSON(), nullable=False),
    sa.Column('trusted_addresses', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('names', sa.JSON(), server_default='{}', nullable=False),
    sa.Column('alert_types', sa.JSON(), nullable=False),
    sa.Column('alert_thresholds', sa.JSON(), nullable=False),
    sa.Column('alerts_enabled', sa.Boolean(), nullable=False),
    sa.Column('state', sa.String(length=16), server_default='member', nullable=False),
    sa.Column('banned_at', UTCDateTime(), nullable=True),
    sa.Column('banned_by', sa.BigInteger(), nullable=True),
    sa.Column('last_seen_at', UTCDateTime(), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.Column('updated_at', UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_table('bag_slots',
    sa.Column('address', sa.String(length=64), nullable=False),
    sa.Column('provider_pubkey', sa.String(length=64), nullable=False),
    sa.Column('last_proof_at', UTCDateTime(), nullable=True),
    sa.Column('payment_max_span', sa.Integer(), nullable=True),
    sa.Column('rate_per_mb_day', sa.BigInteger(), nullable=True),
    sa.Column('next_proof_byte', sa.BigInteger(), nullable=True),
    sa.Column('nonce', sa.String(length=20), nullable=True),
    sa.Column('state', sa.String(length=16), server_default='downloading', nullable=False),
    sa.Column('reason', sa.Integer(), nullable=True),
    sa.Column('reason_at', UTCDateTime(), nullable=True),
    sa.Column('slow_at', UTCDateTime(), nullable=True),
    sa.Column('created_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['address'], ['bags.address'], name=op.f('fk_bag_slots_address_bags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('address', 'provider_pubkey', name=op.f('pk_bag_slots'))
    )
    with op.batch_alter_table('bag_slots', schema=None) as batch_op:
        batch_op.create_index('ix_bag_slots_last_proof_at', ['last_proof_at'], unique=False)
        batch_op.create_index('ix_bag_slots_provider_pubkey', ['provider_pubkey'], unique=False)
        batch_op.create_index('ix_bag_slots_reason', ['reason'], unique=False)
        batch_op.create_index('ix_bag_slots_state', ['state'], unique=False)

    op.create_table('subscriptions',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('provider_pubkey', sa.String(length=64), nullable=False),
    sa.Column('telemetry_pass', sa.String(length=255), nullable=True),
    sa.Column('alerts_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['provider_pubkey'], ['providers.pubkey'], name=op.f('fk_subscriptions_provider_pubkey_providers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_subscriptions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'provider_pubkey', name=op.f('pk_subscriptions'))
    )
    op.create_table('alerts',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('provider_pubkey', sa.String(length=64), nullable=False),
    sa.Column('alert_type', sa.String(length=32), nullable=False),
    sa.Column('notified_at', UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id', 'provider_pubkey'], ['subscriptions.user_id', 'subscriptions.provider_pubkey'], name=op.f('fk_alerts_user_id_subscriptions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'provider_pubkey', 'alert_type', name=op.f('pk_alerts'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alerts')
    op.drop_table('subscriptions')
    with op.batch_alter_table('bag_slots', schema=None) as batch_op:
        batch_op.drop_index('ix_bag_slots_state')
        batch_op.drop_index('ix_bag_slots_reason')
        batch_op.drop_index('ix_bag_slots_provider_pubkey')
        batch_op.drop_index('ix_bag_slots_last_proof_at')

    op.drop_table('bag_slots')
    op.drop_table('users')
    with op.batch_alter_table('providers_history', schema=None) as batch_op:
        batch_op.drop_index('ix_providers_history_archived_at')

    op.drop_table('providers_history')
    op.drop_table('providers')
    with op.batch_alter_table('bags', schema=None) as batch_op:
        batch_op.drop_index('ix_bags_unpaid_at')
        batch_op.drop_index('ix_bags_state')
        batch_op.drop_index('ix_bags_owner_address')
        batch_op.drop_index('ix_bags_bag_id')

    op.drop_table('bags')
    op.drop_table('alert_channels')
    # ### end Alembic commands ###
